PNDA-4513: Flink Metrics - Configure Graphite Metrics reporter
pndaproject/platform-salt pull request #484
Opened 2018-04-09 12:28 UTC by GaneshManal

# Problem Statement:
PNDA-4513: Flink Metrics - Configure Graphite Metrics reporter

# Changes:
Below configurations are required -
- Update flink file ( .yaml ) for configuring graphite as reporter for monitoring data. 
- Copy dependency jars ( for graphite ) from packaged opt to the flink lib.
- Configure graphite whitelist for reading flink monitor logs.

# Test details:
Verified for AWS:
UBUNTU - PICO -CDH & HDP
UBUNTU - STD -CDH & HDP
RHEL - PICO -CDH & HDP
RHEL - STD -CDH & HDP

2018-04-09 14:40 UTC, trsmith2 requested changes
If the code is sending metrics towards graphite then it should target a graphite role, not an edge node role

2018-04-18 12:53 UTC, jeclarke requested changes

2018-04-18 12:53 UTC, jeclarke commented on salt/flink/init.sls
> +{% set edge_nodes = salt['pnda.get_hosts_for_role']('hadoop_edge') %}
Use the specific graphite role, rather than assuming it will be on the hadoop-edge node.

2018-04-18 12:53 UTC, jeclarke commented on salt/flink/init.sls
> +flink_metric_dep_jars-copy-to-flink-lib:
Use the salt file.copy state rather than cmd.run.

2018-04-20 13:25 UTC, jgarnier requested changes
add minor comment and could you rebase it with develop as there is currently some conflicts. thanks

2018-04-20 13:25 UTC, jgarnier commented on salt/flink/init.sls
> +copy_dependency_jar-{{ filename }}:
could you prefix the state id with flink- please?

2018-04-24 09:48 UTC, merged