PNDA-4510: Logrotate not working for /var/log/pnda
pndaproject/platform-salt pull request #486
Opened 2018-04-12 09:13 UTC by mrunmayeejog

# Problem Statement:
PNDA-4510: Logrotate not working for /var/log/pnda

# Analysis:
Logrotate is not functioning as expected for rotating logs in /var/log/pnda. On manual execution prompts error for insecure permissions. To fix this error added su directive to the configurations in order to specify the user/group to be used for log rotation. 

# Changes:
Modified salt script to copy logrotate.conf as a template to which the group name is passed as a variable. The variable is added to pillar which is read in the salt script and based on OS corresponding group name is passed to logrotate.conf file.

# Test details
RHEL - STD - HDP
RHEL - PICO - CDH & HDP
UBUNTU - PICO - CDH & HDP

2018-04-18 12:46 UTC, jeclarke requested changes
This can be simplified now we're not supporting Ubuntu anymore, thanks.

2018-04-18 12:46 UTC, jeclarke commented on pillar/services.sls
> +  ubuntu_group_name: "syslog"
Can remove these

2018-04-18 12:46 UTC, jeclarke commented on salt/logserver/logserver.sls
> +{% if grains['os'] == 'Ubuntu' %}
Remove the ubuntu option and just leave RHEL/CentOS with no conditional.

2018-04-18 12:46 UTC, jeclarke commented on salt/logserver/logserver_templates/logrotate.conf.tpl
> +    su root {{ group_name }}
hard code the group name to root for RHEL/CentOS

2018-04-18 12:46 UTC, jeclarke commented on salt/logserver/logserver.sls
> +    - source: salt://logserver/logserver_templates/logrotate.conf.tpl
move back to 'files'

2018-04-18 13:07 UTC, mrunmayeejog commented on salt/logserver/logserver.sls
> +    - source: salt://logserver/logserver_templates/logrotate.conf.tpl
Will do the required changes

2018-04-19 08:17 UTC, mrunmayeejog commented
Updated suggested changes and hard coded the group name for RHEL/Centos. Please review the same.

2018-04-20 09:20 UTC, jeclarke approved these changes

2018-04-20 09:21 UTC, merged