PNDA-4075: Number of data volumes to be configurable in pnda_env.yaml…
pndaproject/platform-salt pull request #502
Opened 2018-04-28 05:46 UTC by SivaMaplelabs

… to allow multiple data drives to be used

Analysis
Number of data volumes should be configurable in pnda_env.yaml to allow multiple data drives to be used.

Solution
Removed data volumes generation snippet from setup_hadoop.sls.

Files Modified
salt/cdh/setup_hadoop.sls
salt/hdp/setup_hadoop.sls

Tested in  RHEL HDP, RHEL CDH

2018-04-30 09:26 UTC, jeclarke requested changes

2018-04-30 09:26 UTC, jeclarke commented on salt/cdh/setup_hadoop.sls
> -{%- for n in range(flavor_cfg.data_volumes_count) -%}
Remove data_volumes_count from the flavor cfg sls if no longer used (search for data_volumes_count)

2018-05-02 08:08 UTC, jeclarke commented
One more general point, when I wrote this I imagined that the next step would be to have the PNDA CLI would just set data_volumes_count in the pillar (env_parameters instead of the flavour config pillar) and the existing code in platform salt would all just work. Why did you change it to have the PNDA CLI generate the list of volumes and remove the logic from platform-salt?

2018-05-02 11:01 UTC, SivaMaplelabs commented
The reason the logic is removed and added in the pnda-cli is to support the disk configuration for both through pnda_env.yaml and existing machine volume-config.yaml. If this code is not present in pnda-cli, if a user creates volume-config.yaml that contains a different directory name and tries to deploy, deployment fails. In this case user can deploy PNDA both the ways

2018-05-04 12:49 UTC, jeclarke commented
I don't like the direction this is taking, the code has far too many special cases in and will be tough to maintain. I'm going to close the PRs for PNDA-4536 and PNDA-4075 while we consider a better design. Let's discuss over on the JIRA tickets and see what we can come up with.

2018-05-04 12:49 UTC, closed without merging